### ISSUE TITLE
Missed curly brackets in lesson walkthrough results in type error

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/redux-dispatch-with-event-listeners#13]
As per lessons instructions: 
"Now, if instead we want to show the number zero, our default state, well we can just refresh our page, and then dispatch an action that returns the default state like so: dispatch(type: '@@INIT'). "
Results in the following error:
SyntaxError: missing ) after argument list

Correct console command should be: 
dispatch({type: '@@INIT'})

**Comment by maxwellbenton** [comment]
Hi @atxrenegade,

Thank you for spotting this issue and providing this feedback. We've corrected the text in this section to include the necessary curly braces, which should resolve this issue.

Thank you for contributing to a Learn lesson!
