### ISSUE TITLE
Event Listener Should Be Refactored To Use Arrow Function

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/redux-dispatch-with-event-listeners#14]
It's best practice, plus it avoids scoping errors in callbacks.

**Comment by maxwellbenton** [comment]
Hi @RylanBauermeister,

Thank you for spotting this issue. I've updated the example code in the Readme and the solution code to use an arrow function, which should resolve this issue.

Thank you for contributing!
