### ISSUE TITLE
dot-learn file missing

### ISSUE THREAD

**Issue by artrexdenthur** [learn-co-curriculum/redux-dispatch-with-event-listeners#15]
This exercise does not have a .learn file, which causes learn-open (1.2.28) to break when LearnOpen>Lesssons>IosLesson fails to find a :languages key there (/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6)

**Comment by maxwellbenton** [comment]
Hi @artrexdenthur,

Thank you for spotting this and providing feedback. We've added a `.learn` file, which should resolve this issue going forward.

Thank you for contributing!
