### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by wendisha** [learn-co-curriculum/redux-dispatch-with-event-listeners#16]
..."Here it is: you click on a button, and you see a number on the page go to zero to one."
**Should be:**  
Here it is: you click on a button, and you see a number on the page go **from** zero to one.

**Comment by maxwellbenton** [comment]
Hi @wendisha,

Thanks for catching this and providing feedback. We've updated the readme with this fix, so this issue should now be resolved.

Thank you for contributing!
