### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by blainelawson** [learn-co-curriculum/redux-dispatch-with-event-listeners#17]
This makes following along this code-along near impossible.

**Comment by maxwellbenton** [comment]
Hi @blainelawson,

Thank you for providing this feedback. We've added a package.json file and updated this lesson to include some additional instructions for following along, which should help make this lesson easier to follow for future students.

We apologize for any frustration this lesson may have caused you, but we appreciate you taking the time to provide feedback and help improve our curriculum for future students!

Thank you!
