### ISSUE TITLE
Two code snippets telling students different things.

### ISSUE THREAD

**Issue by EoghanL** [learn-co-curriculum/redux-dispatch-with-event-listeners#4]
> function render(){
       let container = document.getElementById('container');
       container.textContent = state.count;
}

The above code snippet is from directly below `3. Using the render function to display our state` which conflicts with what is being shown later on in the readme in the last snippet of section 4 which includes 

> function render() {
    document.setInnerHtml = state.count;
}

**Comment by JessRudder** [comment]
Closed by #6
